In [2]:
import pandas as pd
import numpy as np
# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# pd.set_option('display.max_colwidth', -1)

In [3]:
climate = pd.read_excel('data/bank_climate.xlsx', header=1)

In [5]:
bank_lst = ['Wells Fargo', 'JPMorgan Chase', 'Fairway Independent Mortgage', 'Caliber Home Loans', 'U.S. Bank', 
           'Loan Depot', 'Bank of America']

In [34]:
climate_dict = {}
for bank in bank_lst: 
    val = climate[climate['Bank'].str.contains(bank)]['Total'].values
    climate_dict[bank] = val

In [33]:
climate[climate['Bank'].str.contains('JPMorgan Chase')]['Total'].values

array([2.68593448e+11])

In [30]:
climate_dict['Wells Fargo']  = 197913994353.87134

In [35]:
climate_dict

{'Wells Fargo': array([1.97913994e+11]),
 'JPMorgan Chase': array([2.68593448e+11]),
 'Fairway Independent Mortgage': array([], dtype=float64),
 'Caliber Home Loans': array([], dtype=float64),
 'U.S. Bank': array([], dtype=float64),
 'Loan Depot': array([], dtype=float64),
 'Bank of America': array([1.56924771e+11])}

In [4]:
climate

,Rank,Bank,2016,2017,2018,2019,Total
0,1.0,JPMorgan Chase,6.398598e+10,7.065434e+10,6.902773e+10,6.492540e+10,2.685934e+11
1,2.0,Wells Fargo,3.450441e+10,5.493113e+10,6.323693e+10,4.524152e+10,1.979140e+11
2,3.0,Citi,4.306561e+10,4.609018e+10,4.610078e+10,5.240896e+10,1.876655e+11
3,4.0,Bank of America,3.759267e+10,3.633119e+10,3.492580e+10,4.807511e+10,1.569248e+11
4,5.0,RBC,3.034578e+10,3.826808e+10,3.696151e+10,3.510766e+10,1.406830e+11
5,6.0,MUFG,2.564022e+10,2.705585e+10,3.387926e+10,3.223524e+10,1.188106e+11
6,7.0,Barclays,3.107220e+10,3.073316e+10,2.663340e+10,2.966713e+10,1.181059e+11
7,8.0,TD,2.032776e+10,2.907064e+10,2.613953e+10,2.789294e+10,1.034309e+11
8,9.0,Mizuho,2.182636e+10,1.986136e+10,2.919070e+10,3.220083e+10,1.030792e+11
9,10.0,Scotiabank,1.878630e+10,2.387578e+10,2.904301e+10,2.604004e+10,9.774512e+10
10,11.0,Morgan Stanley,2.444127e+10,2.477241e+10,1.992929e+10,2.282631e+10,9.196929e+10
11,12.0,HSBC,1.781424e+10,2.231901e+10,1.984658e+10,2.654859e+10,8.652843e+10
12,13.0,BNP Paribas,1.776213e+10,1.806923e+10,1.777417e+10,3.061798e+10,8.422350e+10
13,14.0,Goldman Sachs,2.360930e+10,2.037219e+10,1.767803e+10,2.209458e+10,8.375411e+10
14,15.0,Bank of China,2.341018e+10,1.598692e+10,2.342313e+10,2.085622e+10,8.367644e+10
15,16.0,Bank of Montreal,1.727048e+10,2.121164e+10,2.116011e+10,2.247237e+10,8.211460e+10
16,17.0,Credit Suisse,1.984918e+10,2.233325e+10,1.745561e+10,1.466662e+10,7.430467e+10
17,18.0,ICBC,1.930654e+10,1.373122e+10,1.519609e+10,2.070600e+10,6.893986e+10
18,19.0,Deutsche Bank,2.175055e+10,1.991565e+10,1.531172e+10,1.190695e+10,6.888487e+10
19,20.0,SMBC Group,1.103747e+10,1.242255e+10,1.592687e+10,2.017204e+10,5.955893e+10
20,21.0,CIBC,1.221751e+10,1.412913e+10,1.200016e+10,1.938121e+10,5.772800e+10
21,22.0,Société Générale,1.364565e+10,1.151211e+10,1.368872e+10,1.525234e+10,5.409882e+10
22,23.0,China Construction Bank,1.678421e+10,1.090212e+10,9.227136e+09,1.423442e+10,5.114789e+10
23,24.0,Crédit Agricole,8.798998e+09,1.144714e+10,1.327400e+10,1.234321e+10,4.586335e+10
24,25.0,ING,9.718022e+09,8.303748e+09,1.083119e+10,8.608830e+09,3.746179e+10
25,26.0,Agricultural Bank of China,1.208436e+10,5.416748e+09,7.240190e+09,1.120341e+10,3.594471e+10
26,27.0,UBS,8.383667e+09,9.457167e+09,1.080395e+10,6.416061e+09,3.506084e+10
27,28.0,BPCE/Natixis,5.612034e+09,6.473919e+09,1.065871e+10,7.737986e+09,3.048265e+10
28,29.0,Santander,6.300660e+09,5.334857e+09,5.123481e+09,8.977394e+09,2.573639e+10
29,30.0,Standard Chartered,2.344172e+09,4.869129e+09,8.806950e+09,7.997015e+09,2.401727e+10
30,31.0,UniCredit,6.691785e+09,7.031911e+09,4.839718e+09,4.681808e+09,2.324522e+10
31,32.0,BBVA,4.741337e+09,3.368187e+09,4.550898e+09,4.791718e+09,1.745214e+10
32,33.0,Intesa Sanpaolo,4.201111e+09,1.920111e+09,4.175826e+09,1.820829e+09,1.211788e+10
33,34.0,RBS,3.740524e+09,3.028751e+09,3.655064e+09,1.692096e+09,1.211643e+10
34,35.0,Commerzbank,1.076664e+09,2.565136e+09,2.546343e+09,3.816959e+09,1.000510e+10
35,NaN,Grand Total,6.397394e+11,6.737659e+11,7.002626e+11,7.356178e+11,2.749386e+12

In [4]:
# sustainable finance commitments 
susfin = pd.read_excel('data/sustainable_finance_commitments.xlsx', header=1)

In [5]:
susfin.columns
susfin.iloc[2]['Detailed\ndescription of criteria\nand/or list of activities,\nthemes, and/or sectors']

'The commitment is designated for developing clean energy, lower-carbon technologies, and projects that contribute to the delivery of the Paris Climate Agreement and the UN Sustainable Development Goals.'

In [6]:
susfin.head()

,Bank name,Location of bank headquarters,"Total assets (billions, USD; S&P 2018)",Total assets (USD; S&P 2018),Does the bank have a sustainable finance commitment?,Commitment in USD,Commitment description,1. Defines sustainability criteria.,"Detailed\ndescription of criteria\nand/or list of activities,\nthemes, and/or sectors",2. Identifies financial services included.,Description of the\ntypes of financial services\nincluded,3. Provides specific timeline.,Details\nabout the start and end\ndate of the commitment,1. Discloses accounting methodology.,Details about\nwhere the methodology is\npublished,2. Includes plans for reporting.,Details about\nwhat/how the bank will\nreport,3. Endorsed by CEO/board chair.,Details about\nwho endorsed the\ncommitment,1. Annualized commitment in USD,"2. Average annual fossil fuel finance in USD (2016-2018; sourced from RAN, 2019)",3a. Bank size by average total assets in USD (2016-2018),3b. Bank size by average annual revenue in USD (2016-2018),New or renewal?,"Type of commitment (Stock, Flow or Combination)?","Type of finance included, classified by WRI based on public information (lending, equity investment, grant, facilitation of (debt/equity) capital raising, advisory for merger & acquisition, insurance and other risk hedging products, internal spending on sustainability programs, asset management service, unclear)",Web presence of the commitment,Year 1 (beginning of commitment),End year,Start year with month,End year with month,Total commitment (in currency of bank),Commitment currency \n(if not USD),Timespan of commitment (# years)\n,Year 0\n,Exchange rate to USD in year 1,Sustainable finance at year 0 (in bank currency),"Definition of sustainable finance, other notes (for year 0)",Currency,"Exchange rate, 2018 (USD equivalent of 1 unit of currency)","Exchange rate, 2017 (USD equivalent of 1 unit of currency)","Exchange rate, 2016 (USD equivalent of 1 unit of currency)","Assets, 2018 (in bank currency)","Assets, 2017 (in bank currency)","Assets, 2016 (in bank currency)","Assets, 2018 (USD)","Assets, 2017 (USD)","Assets, 2016 (USD)","Average assets, 2016-2018 (USD)","Revenue, 2018 (in bank currency)","Revenue, 2017 (in bank currency)","Revenue, 2016 (in bank currency)",Notes on revenue,Further notes,"Revenue, 2018 (USD)","Revenue, 2017 (USD)","Revenue, 2017 (USD).1","Average revenue, 2016-2018 (USD)","RAN total fossil fuel, 2018 (USD)","RAN total fossil fuel, 2017 (USD)","RAN total fossil fuel, 2016 (USD)","Average total fossil fuel, 2016-2018 (USD)",Link to press release (if available),Supplemental reference,Additional supplemental reference,Unnamed: 65,Exchange rate data inputs (used to convert values to USD),Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74
0,JPMorgan Chase & Co.,US,2533.60,2.533600e+12,Yes,200000000000,JPMorgan Chase & Co. committed to facilitating...,Yes,The commitment is designated for facilitating ...,Yes,The bank gives examples of services it provide...,Vague,The announcement was made in July 2017. The co...,No,Although the bank provides several specific ex...,Yes,A reporting plan was not mentioned in the anno...,Yes,The Chairman and CEO is quoted in the press re...,2.222222e+10,6.522107e+10,2.549035e+12,1.021010e+11,New,Flow,"Equity investment, facilitation of (debt/equit...","""Sustainability"" webpage",2016.0,2025.0,2016-01-01,2025-12-31,2.000000e+11,NaN,9.0,2015.0,1.0000,NaN,The bank does not have the baseline number. Fr...,USD,1.0000,1.0000,1.0000,2.622532e+12,2.533600e+12,2.490972e+12,2.622532e+12,2.533600e+12,2.490972e+12,2.549035e+12,1.090290e+11,1.007050e+11,9.656900e+10,Total net revenue,NaN,1.090290e+11,1.007050e+11,9.656900e+10,1.021010e+11,6.390310e+10,6.904580e+10,6.271430e+10,6.522107e+10,https://www.jpmorganchase.com/corporate/Corpor...,NaN,NaN,NaN,Exchange rate to USD,NaN,NaN,NaN,2018 Average exchange rates,NaN,NaN,NaN,NaN
1,Wells Fargo & Co.,US,1951.76,1.951760e+12,Yes,200000000000,Wells Fargo & Co committed to providing $200 b...,Yes,The commitment indicates more than 50 percent ...,Yes,"The commitment includes sustainability loans, ...",Specific,The announcement was made in April 2018. The a...,Yes,A detailed accounting methodology is provided ...,Yes,The announcement indicated the bank would prov...,Yes,The CEO made the announcement.,1.538462e+10,5.053287e+10,1.925918e+12,8.768800e+10,Renewal,Combination,"Lending, equity investments, facilitation of (...","""Environmental Sustainability"" webpage",2018.0,2030.0,2018-01-01,2030-12-31,2.000000e+11,NaN,13.0,2017.0,1.0000,17800000000,Broad definitions remain the same; but differe...,USD,1.0000,1.0000,1.0000,1.895883e+12,1.951757e+12,1.930115e+12,1.895883e+12,1.951757e+12,1.930115e+12,1.925918e+12,8.640800e+10,8.838900e+10,8.826700e+10,Net interest income + Total noninterest income,NaN,8.640800e+10,8.838900e+10,8.826700e+10,8.768800e+10,6.135092e+10,5.420681e+10,3.604088e+10,5.053287e+10,https://newsroom.wf.com/press-release/corporat...,NaN,NaN,NaN,Year,USD,Foreign currency,NaN,NaN,Foreign currency,USD,Foreign currency,USD
2,HSBC,UK,2521.77,2.521770e+12,Yes,100000000000,HSBC committed to providing $100 billion in su...,Yes,The commitment is designated for developing cl...,Yes,The commitment includes facilitation (advisory...,Specific,The start date is not explicitly stated in the...,Yes,"The bank defines sustainable finance as ""any f...",Yes,The reporting plan was not mentioned in the an...,Yes,The CEO is quoted in the announcement.,1.111111e+10,1.926924e+10,2.484960e+12,5.106367e+10,New,Combination,"Lending, facilitation of (debt/equity) capital...","""Sustainable Finance"" webpage",2017.0,2025.0,2017-01-01,2025-12-31,1.000000e+11,NaN,9.0,2016.0,1.0000,NaN,The bank does not have the baseline number. Bu...,USD,1.0000,1.0000,1.0000,2.558124e+12,2.521771e+12,2.374986e+12,2.558124e+12,2.521771e+12,2.374986e+12,2.484960e+12,5.378000e+10,5.144500e+10,4.796600e+10,Net operating income before change in expected...,NaN,5.378000e+10,5.144500e+10,4.796600e+10,5.106367e+10,1.879107e+10,2.155553e+10,1.746113e+10,1.926924e+10,https://www.hsbc.com/media/media-releases/2017...,NaN,NaN,NaN,2016,1.1072,EUR,NaN,EUR,1,1.1817,0.846238,1
3,Bank of America,US,2281.23,2.281230e+12,Yes,300000000000,Bank of America committed to mobilizing an add...,Yes,The finance is designated for promoting low-ca...,Yes,"The commitment includes lending, investing, ca...",Specific,The start year was not specified in the announ...,No,The accounting methodology is not described.,Yes,A reporting plan was not mentioned in the anno...,Yes,The Vice Chairman is quoted in the press relea...,2.727273e+10,3.556223e+10,2.274603e+12,8.743333e+10,Renewal,Flow,"Lending, equity investment, facilitation of (d...","""Corporate Environmental Sustainability at Ban...",2020.0,2030.0,2020-01-01,2030-12-01,3.000000e+11,NaN,11.0,2018.0,1.0000,21500000000,NaN,USD,1.0000,1.0000,1.0000,2.354507e+12,2.281234e+12,2.188067e+12,2.354507e+12,2.281234e+12,2.188067e+12,2.274603e+12,9.124700e+10,8.735200e+10,8.370100e+10,"Total revenue, net of interest expense",NaN,9.124700e+10,8.735200e+10,8.370100e+10,8.743333e+10,3.374523e+10,3.687947e+10,3.606199e+10,3.556223e+10,https://newsroom.bankofamerica.com/press-relea...,https://about.bankofamerica.com/en-us/what-gui...,NaN,NaN,2017,1.1301,EUR,NaN,CAD,1,0.771784,1.2957,1
4,Crédit Agricole Group,France,2117.16,2.117160e+12,Yes,26572800000,Crédit Agricole Group committed doubling the s...,No,"The commitments are for green loans, SRI loans...",Yes,"The commmitments include loans, bonds, and ass...",Specific,Timelines of the two most recent pledges are s...,No,The accounting methodology is not described.,No,A reporting plan was not mentioned in the anno...,No,No senior management commentary found on the c...,3.796114e+09,1.072058e+10,1.786384e+12,2.101332e+10,New,Stock,"Lending, asset management service","""Climate Finance"" webpage - climate strategy d...",2016.0,2022.0,2016-01-01,2022-12-31,2.400000e+10,EUR,7.0,2015.0,1.1072,NaN,NaN,EUR,1.1817,1.1301,1.1072,1.624394e+12,1.550283e+12,1.524232e+12,1.919546e+12,1.751975e+12,1.687630e+12,1.786384e+12,1.973600e+10,1.863400e+10,1.685300e+10,Revenues,NaN,2.332203e+10,2.105828e+10,1.865964e+10,2.101332e+10,1.261750e+10,1.086689e+10,8.677345e+09,1.072058e+10,https://pressroom.credit-agricole.com/news/cre...,https://pressroom.credit-agricole.com/news/cli...,NaN,NaN,2018,1.1817,EUR,NaN,AUD,1,0.7481,1.33672,1