In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, SGDClassifier
from sklearn.model_selection import KFold, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, precision_score, recall_score, roc_auc_score, roc_curve
from yellowbrick.target import ClassBalance
import seaborn as sns
import itertools
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [103]:
# Load the data and create a copy to use to verify preprocessing steps
quicken_df = pd.read_csv('data/quicken_2019.csv')
check_df = quicken_df.copy()
# Pull Census Tract dictionary from different notebook
%store -r FIPS_dict

# Step 1: Condense High Cardinality Variables
Action Taken: 
* 1: Loan originated
* 2: Application approved but not accepted
* 3: Application denied
* 4: Application withdrawn by applicant
* 5: File closed for incompleteness
* 6: Purchased loan
* 7: Preapproval request denied
* 8: Preapproval request approved but not accepted

Interpreting which actions are 'approved:' 
1, 2, 6

Denied:
3

Irrelevant to model: 4, 5, 7, 8

-------
* Race and Ethnicity columns both allow the applicant to report a more specific value. For example, an applicant can select Asian (2) or more specifically Chinese(22), etc. Because this column will be onehotencoded, I'm going to simplify these columns to the top-level categories:
    - American Indian or Alaska Native
    - Asian
    - Black or African American
    - Native Hawaiian or Other Pacific Islander
    - White
    - Hispanic
    - Non-Hispanic
------------

Census Tract
* The Census Tract column contains ~65K unique values, 366 of which are NA. These were mapped to 10 'primary codes' which indicate if a region is rural, urban, metropolitan, etc. However, because I couldn't use the mapper dictionary if null values were present, dropped these in this preprocessing step rather than in the general missing values section, below.

In [104]:
# action taken
quicken_df = quicken_df[~quicken_df['action_taken'].isin([4,5,7,8])]
quicken_df['action_taken'] = quicken_df['action_taken'].map(lambda x: 0 if x ==3 else 1)

# applicant race 
def condense_race(x): 
    if x == 6 or x == 7:
        x = np.nan
    if x> 10 and x < 20: 
        x = 1
    if x> 20 and x < 30: 
        x = 2
    if x> 40 and x < 50: 
        x = 4
    else: 
        x = x
    return x

# applicant ethnicity
def condense_ethnicity(x): 
    if x == 3 or x == 4: 
        x = np.nan
    if x !=2: 
        x = 1
    else: 
        x = x
    return x 

def condense_sex(x): 
    if x == 3 or x == 4: 
        x = np.nan
    else: 
        x = x
    return x

In [105]:
quicken_df['applicant_race-1'] = quicken_df['applicant_race-1'].apply(lambda x: condense_race(x))
quicken_df['applicant_ethnicity-1'] = quicken_df['applicant_ethnicity-1'].apply(lambda x: condense_ethnicity(x))
quicken_df['applicant_sex'] = quicken_df['applicant_sex'].apply(lambda x: condense_sex(x))

quicken_df = quicken_df.dropna(subset=['census_tract'])
quicken_df['census_tract'] = quicken_df['census_tract'].astype(int)
quicken_df['census_tract'] = quicken_df['census_tract'].astype(str)
quicken_df['census_tract'] = quicken_df['census_tract'].map(FIPS_dict)

# Step 2: Feature Engineering
* Planned to add the following columns: 
    - has co-signer
    - bi/multi-racial
    - co-signer bi/multi-racial
    
However, FFEIC updated their datasets with new "derived" variables, which already achieve this goal for race, ethnicity, and sex. These values don't add up to the original field. Will use both for now. 

* Ordinal Encoding for Age column
* DIR contains str and int, mapped using dictionary

In [106]:
# Create ordinalencoder object
enc = OrdinalEncoder()

# Convert column to array
age_df = quicken_df[['applicant_age']].to_numpy()
enc.fit(age_df)
enc.categories_

# fitted encoder to array
enc_age_arr = enc.transform(quicken_df[['applicant_age']].to_numpy())

# Apply encoder transformation
quicken_df['applicant_age'] = enc_age_arr

In [107]:
DIR_mapper = {'20%-<30%': 25, '30%-<36%': 33, '>60%': 65, '<20%': 15, '50%-60%': 55}


quicken_df['debt_to_income_ratio'] = quicken_df['debt_to_income_ratio'] \
                                    .map(lambda x: DIR_mapper[x] if x in DIR_mapper else int(x), na_action='ignore')

# Step 3: Missing Values
1. Some variables are perfect predictors when they are null. Filled all nan values with 99 so I could run a crosstabulation to check for this.

In [109]:
quicken_df = quicken_df.fillna(99)

In [227]:
# Impute median for nan in the following columns
quicken_df['debt_to_income_ratio'] = quicken_df['debt_to_income_ratio'].fillna(quicken_df['debt_to_income_ratio'] \
                                                                               .median())
quicken_df['income'] = quicken_df['income'].fillna(quicken_df['income'].median())
quicken_df['property_value'] = quicken_df['property_value'].fillna(quicken_df['property_value'].median())
quicken_df['income'] = quicken_df['income'].fillna(quicken_df['income'].median())
quicken_df['loan_to_value_ratio'] = quicken_df['loan_to_value_ratio'].fillna(quicken_df['loan_to_value_ratio'] \
                                                                             .median())

# Step 4: Feature Selection
1. Drop columns containing only one unique value
Null values are represented differently for each variable in the dataset. Looked at each variable and recoded null values to 99 where applicable
2. Check for perfect predictors and drop those
3. Drop certain columns based on what information is relevant. This will apply to all lenders
    a. ```state_code``` and ```county_code``` - using census tract and ```derived_msa-md``` because they are more informative
4. ```Income``` converted na back to np.nan and will impute median for this column
5. There are several census features that were appended to the dataset after the lender submitted their report. While these features might be used in a different part of this study, they will be excluded from the dataset that will be fed into the model, as the bank did not report these values. 
6. Exclude 2nd lien mortgage, interest only payment loans (only ~400 of these loans)

In [8]:
perfect_predictors = []
for col in quicken_df.columns: 
    cross = pd.crosstab(quicken_df[col], quicken_df['action_taken'])
    if cross[0].sum() == 0 or cross[1].sum() == 0:
        perfect_predictors.append(col)
perfect_predictors

[]

In [110]:
one_unique_value_lst = []
for col in quicken_df.columns:
    if len(quicken_df[col].unique()) ==1: 
        one_unique_value_lst.append(col)
quicken_df = quicken_df.drop(one_unique_value_lst, axis=1)

In [147]:
# null coded as 99999, 0, 5 --> recode to 99
quicken_df['derived_msa-md'] = quicken_df['derived_msa-md'].apply(lambda x: 99 if x == 99999 else x)
quicken_df['purchaser_type'] = quicken_df['purchaser_type'].apply(lambda x: 99 if x == 0 else x)
quicken_df['loan_purpose'] = quicken_df['loan_purpose'].apply(lambda x: 99 if x == 5 else x)
quicken_df['applicant_credit_score_type'] = quicken_df['applicant_credit_score_type'] \
                                                    .apply(lambda x: 99 if x == 9 else x)
quicken_df['applicant_ethnicity_observed'] = quicken_df['applicant_ethnicity_observed'] \
                                                    .apply(lambda x: 99 if x == 3 else x)
quicken_df['applicant_race_observed'] = quicken_df['applicant_race_observed'] \
                                                    .apply(lambda x: 99 if x == 3 else x)
quicken_df['submission_of_application'] = quicken_df['submission_of_application'] \
                                                    .apply(lambda x: 99 if x == 3 else x)

In [169]:
# Columns to drop b/c irrelevant or class imbalance is extreme 
drop_irrelevant = ['state_code', 'county_code', 'open-end_line_of_credit', 'manufactured_home_land_property_interest', 
                  'manufactured_home_secured_property_type', 'co-applicant_credit_score_type', 'applicant_ethnicity-2',
                  'applicant_ethnicity-3', 'applicant_ethnicity-4', 'co-applicant_ethnicity-1', 'co-applicant_ethnicity-2',
                  'co-applicant_ethnicity-3', 'co-applicant_ethnicity-4', 'co-applicant_ethnicity_observed',
                  'applicant_race-2', 'applicant_race-3', 'applicant_race-4', 'applicant_race-5', 
                  'co-applicant_race-1', 'co-applicant_race-2', 'co-applicant_race-3', 'co-applicant_race-4', 
                  'co-applicant_race-5', 'co-applicant_race_observed', 'co-applicant_sex', 'applicant_sex_observed',
                  'co-applicant_sex_observed', 'co-applicant_age', 'applicant_age_above_62', 'co-applicant_age_above_62',
                  'submission_of_application', 'derived_loan_product_type', 'interest_only_payment']

confirmed_perfect_pred = ['denial_reason-1', 'denial_reason-2', 'denial_reason-3', 'purchaser_type', 'preapproval', 
                       'interest_rate', 'rate_spread', 'hoepa_status', 'total_loan_costs', 'origination_charges', 
                       'discount_points', 'lender_credits', 'initially_payable_to_institution']

census_appended = ['tract_minority_population_percent', 'tract_population', 'ffiec_msa_md_median_family_income',
                  'tract_to_msa_income_percentage', 'tract_owner_occupied_units', 'tract_one_to_four_family_homes',
                  'tract_median_age_of_housing_units']

In [197]:
quicken_df = quicken_df.drop(drop_irrelevant + confirmed_perf_pred + census_appended, axis=1)

In [183]:
# Subselections of relevant variables
quicken_df = quicken_df[quicken_df['lien_status'] == 1]

In [200]:
# Recode 99 back to np.nan to further impute values
quicken_df = quicken_df.applymap(lambda x: np.nan if x == 99 else x)

In [224]:
# If the percentage of NON null values is under 5% of the entire dataset, drop column
mostly_null = []
for col in quicken_df.columns: 
    if quicken_df[col].notnull().sum()/quicken_df.shape[0] * 100 <5:
        mostly_null.append(col)
quicken_df = quicken_df.drop(mostly_null, axis=1)

In [228]:
# create list of columns that have null values that need to be handled
has_nulls = []
for col in quicken_df.columns: 
    if quicken_df[col].notnull().sum() != quicken_df.shape[0]: 
        has_nulls.append(col)
has_nulls

['derived_msa-md',
 'census_tract',
 'applicant_credit_score_type',
 'applicant_ethnicity_observed',
 'applicant_race-1',
 'applicant_race_observed',
 'applicant_sex']

In [ ]:
# If the percentage of NON null values is under 5% of the entire dataset, drop column
for col in quicken_df.columns: 
    if quicken_df[col].notnull().sum()/quicken_df.shape[0] * 100 < 5:
        mostly_null.append(col)

In [235]:
# Calculate missing value ratio for remaining columns with null value
missing_val_dict = {}
for col in has_nulls: 
    missing_val_dict[col] = quicken_df[col].isnull().sum()/quicken_df.shape[0]* 100
missing_val_dict

{'derived_msa-md': 11.72221243767161,
 'census_tract': 24.568573499138157,
 'applicant_credit_score_type': 0.33838504869337754,
 'applicant_ethnicity_observed': 0.3378075998048223,
 'applicant_race-1': 37.14324485853946,
 'applicant_race_observed': 0.3378075998048223,
 'applicant_sex': 29.085523067639475}

In [262]:
quicken_df['applicant_credit_score_type'].value_counts(dropna=False)

1.0    247562
3.0    225905
2.0    216891
NaN      2344
Name: applicant_credit_score_type, dtype: int64

# Check to see if values are missing at random
* Variables that might be different "enough" based on the mean:
    * property value
    * loan amount
* However, std is very similar, so I'll assume values are missing at random

In [259]:
# fig, ax = plt.subplots()

census_missing = quicken_df[quicken_df['census_tract'].isnull()]
census_missing.describe().reset_index().iloc[[1]]

,index,derived_msa-md,census_tract,action_taken,loan_type,loan_purpose,lien_status,loan_amount,loan_to_value_ratio,loan_term,property_value,construction_method,occupancy_type,total_units,income,debt_to_income_ratio,applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity_observed,applicant_race-1,applicant_race_observed,applicant_sex,applicant_age,aus-1
1,mean,33033.92635,NaN,0.853626,1.319784,24.814363,1.0,346877.229166,76.452437,336.74853,520241.88099,1.000229,1.114415,1.024502,116.510474,37.767896,1.970713,1.546816,1.998941,4.42258,1.999141,1.325329,2.232568,1.824569

In [257]:
quicken_df.describe().reset_index().iloc[[1]]

,index,derived_msa-md,census_tract,action_taken,loan_type,loan_purpose,lien_status,loan_amount,loan_to_value_ratio,loan_term,property_value,construction_method,occupancy_type,total_units,income,debt_to_income_ratio,applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity_observed,applicant_race-1,applicant_race_observed,applicant_sex,applicant_age,aus-1
1,mean,30837.51435,1.925524,0.816205,1.415401,23.194977,1.0,252907.917113,78.974088,327.320545,353243.3283,1.000361,1.080426,1.019311,99.795794,37.761833,1.968629,1.56628,1.999367,4.565938,1.999518,1.340963,2.283324,1.899609

In [232]:
quicken_df['derived_msa-md'].value_counts()

12060.0    20575
31084.0    19747
38060.0    18932
47664.0    15207
40140.0    13734
47894.0    12232
41740.0    10773
35614.0    10467
36084.0    10138
40900.0    10123
19740.0     9894
16984.0     9816
26420.0     9635
16740.0     8945
45300.0     8443
11244.0     8348
29820.0     8152
19124.0     7712
33460.0     7446
42644.0     7354
19804.0     7324
35154.0     6849
36740.0     6747
12580.0     5702
38900.0     5634
35004.0     5478
34980.0     5211
41940.0     5025
17460.0     4825
35084.0     4511
22744.0     4499
41620.0     4407
26900.0     4369
15764.0     4210
28140.0     4117
33124.0     4011
18140.0     4006
23104.0     3996
27260.0     3908
41180.0     3884
39580.0     3781
38300.0     3665
33874.0     3594
41700.0     3534
14454.0     3512
17140.0     3489
48424.0     3449
40060.0     3378
12420.0     3329
47260.0     3253
37100.0     3023
39300.0     2969
45104.0     2833
23224.0     2802
37964.0     2774
44700.0     2697
15980.0     2691
15804.0     2634
31140.0     2605
35840.0     2594
14260.0     2574
17820.0     2496
32820.0     2481
19660.0     2413
46060.0     2403
24860.0     2299
36260.0     2260
15380.0     2224
41884.0     2173
35380.0     2161
24340.0     2131
39340.0     2111
13820.0     2062
10740.0     2058
23420.0     2057
37340.0     2038
49340.0     2037
36420.0     2002
16700.0     1950
25540.0     1916
39900.0     1908
34820.0     1885
46700.0     1854
29460.0     1790
36540.0     1763
33340.0     1696
12540.0     1661
33700.0     1656
28940.0     1651
38940.0     1636
44060.0     1636
24660.0     1623
10900.0     1612
39100.0     1609
23844.0     1587
14860.0     1585
10420.0     1535
49180.0     1531
42220.0     1530
48864.0     1511
17900.0     1495
29404.0     1471
46140.0     1465
29620.0     1464
40380.0     1392
35300.0     1359
20500.0     1357
22420.0     1324
40484.0     1322
37860.0     1292
20994.0     1288
12940.0     1271
41500.0     1262
10580.0     1260
24540.0     1258
16860.0     1257
22220.0     1243
11700.0     1233
30780.0     1219
11460.0     1203
38860.0     1183
41420.0     1170
19780.0     1163
41540.0     1156
31700.0     1146
45780.0     1119
19430.0     1118
46520.0     1102
26620.0     1100
44140.0     1091
36100.0     1083
12260.0     1060
42340.0     1019
25420.0     1009
22660.0     1001
29420.0     1000
39460.0     1000
30460.0      986
34940.0      977
21660.0      976
36500.0      943
48620.0      929
27140.0      928
39150.0      907
47300.0      896
11260.0      894
15940.0      881
49660.0      879
42540.0      877
25180.0      876
14740.0      863
44180.0      860
12700.0      823
25940.0      819
42200.0      816
22180.0      796
18880.0      796
45060.0      787
28420.0      784
43900.0      764
49620.0      758
45220.0      756
25860.0      755
33660.0      750
29540.0      748
25060.0      738
23060.0      727
42020.0      718
19300.0      711
21340.0      706
40220.0      704
14500.0      695
42100.0      692
45940.0      684
33780.0      683
31340.0      661
48900.0      659
43780.0      657
23580.0      654
33860.0      637
26140.0      635
42034.0      631
13460.0      620
31540.0      604
39740.0      585
32900.0      573
15260.0      567
26580.0      562
32780.0      555
20700.0      554
41100.0      549
28020.0      548
23540.0      545
27100.0      540
42680.0      539
17020.0      538
17660.0      538
32580.0      533
18580.0      531
17300.0      530
29180.0      528
31020.0      524
20260.0      522
28700.0      521
17980.0      515
43340.0      507
39380.0      503
30700.0      501
28660.0      500
16820.0      488
12100.0      484
13380.0      482
21780.0      482
49700.0      472
13140.0      471
19340.0      460
35980.0      460
47580.0      459
40420.0      458
15540.0      455
39820.0      449
49420.0      444
37460.0      432
42140.0      425
29740.0      420
37900.0      417
12020.0      413
16620.0      413
24300.0      405
20100.0      404
24580.0      403
46540.0      398
45540.0      397
27980.0      393
10540.0      392
34900.0      389
34740.0      388
31460.0      388
49020.0      387
27740.0      380
31420.0      379
29340.0      377
35660.0      370
45820.0      361
26820.0      359
21500.0      355
30980.0      354
36140.0      354
21140.0      353
11100.0      351
13740.0      350
22900.0      349
33260.0      346
28740.0      345
26380.0      344
13780.0      343
42700.0      342
40980.0      341
22380.0      340
16940.0      338
46340.0      332
11540.0      332
46220.0      331
47380.0      326
40340.0      325
43620.0      324
15500.0      323
22500.0      320
27340.0      314
34580.0      311
31180.0      310
48300.0      309
16540.0      306
12220.0      304
12980.0      300
39540.0      299
15180.0      299
29200.0      291
12620.0      290
44940.0      289
33740.0      288
14020.0      287
14540.0      285
19460.0      285
27900.0      284
33140.0      280
27500.0      276
25620.0      267
41060.0      265
16180.0      264
22520.0      263
21060.0      261
46300.0      260
44420.0      259
35100.0      258
13980.0      257
10500.0      257
16300.0      256
20940.0      256
45460.0      254
20020.0      249
15680.0      248
44220.0      248
17420.0      240
30140.0      239
24420.0      238
24780.0      238
43580.0      237
24020.0      236
30340.0      235
25260.0      235
49740.0      234
34100.0      233
17780.0      232
43420.0      231
20740.0      229
30860.0      228
46660.0      227
22020.0      227
48540.0      227
16580.0      226
36780.0      225
27180.0      222
26300.0      222
41140.0      222
33540.0      221
31900.0      216
48700.0      214
33220.0      213
25220.0      213
27860.0      212
11500.0      212
16220.0      211
36220.0      210
43300.0      210
23900.0      208
19140.0      207
13220.0      206
17860.0      202
44300.0      202
39660.0      201
48140.0      197
34620.0      191
16060.0      190
36980.0      189
14100.0      188
44100.0      188
40580.0      188
38340.0      186
34060.0      186
28100.0      184
13020.0      184
11020.0      184
21820.0      183
47220.0      182
45500.0      179
48260.0      173
10780.0      167
40660.0      167
25500.0      163
37620.0      163
24500.0      160
11180.0      160
30020.0      159
24140.0      159
27620.0      159
43100.0      158
22140.0      158
29020.0      158
47460.0      157
14010.0      156
38540.0      155
29940.0      152
18020.0      149
18700.0      147
23460.0      146
16020.0      145
10180.0      143
29700.0      141
47940.0      139
19060.0      139
19500.0      138
24220.0      132
25980.0      132
31740.0      130
13900.0      128
41660.0      127
30300.0      126
48060.0      120
29100.0      120
31860.0      118
24260.0      117
47020.0      116
26980.0      115
38220.0      113
48660.0      111
30620.0      110
21300.0      110
22540.0      108
27780.0      105
19180.0       92
21420.0       79
20220.0       78
27060.0       63
Name: derived_msa-md, dtype: int64

# Examine Class Imbalance

In [14]:
boa_df['action_taken'].value_counts()

NameError: name 'boa_df' is not defined

# Examing Colinearity

# Check for Perfect Predictors